DreamFactory v2.0

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -1,189 +1,281 @@
-#!/bin/bash -e
+#!/bin/bash
+set -e
 
-source ${OPENSHIFT_DREAMFACTORY_DIR}usr/php/lib/php_config
 
-HTTPD_CFG_FILE=$OPENSHIFT_DREAMFACTORY_DIR/configuration/etc/conf/httpd_nolog.conf
-HTTPD_CFG_DIR=$OPENSHIFT_DREAMFACTORY_DIR/configuration/etc/conf.d
-ERB_HTTPD_CFG_DIR=$OPENSHIFT_DREAMFACTORY_DIR/usr/php/shared/etc/conf.d/
-HTTPD_PASSENV_FILE=$HTTPD_CFG_DIR/passenv.conf
-HTTPD_PID_FILE=$OPENSHIFT_DREAMFACTORY_DIR/run/httpd.pid
+source ${OPENSHIFT_CARTRIDGE_SDK_BASH}
+source ${OPENSHIFT_PHP_DIR}/lib/util
 
-# construct the configuration directives for httpd
-HTTPD_CMD_CONF="-C 'Include $HTTPD_CFG_DIR/*.conf' -f $HTTPD_CFG_FILE"
-for dir in /etc/openshift/cart.conf.d/httpd{,/php} ; do
-    [ -d $dir ] && HTTPD_CMD_CONF="$HTTPD_CMD_CONF -c 'Include $dir/*.conf'"
-done
+export STOPTIMEOUT=20
+export STARTTIMEOUT=20
 
-function pre_start_httpd_config {
-    write_server_status ${HTTPD_CFG_DIR}/server-status.conf
-    write_httpd_passenv $HTTPD_PASSENV_FILE
-    select_php_document_root ${OPENSHIFT_REPO_DIR}
-    oo-erb ${ERB_HTTPD_CFG_DIR}openshift.conf.erb > ${HTTPD_CFG_DIR}/openshift.conf
-    oo-erb ${OPENSHIFT_DREAMFACTORY_DIR}conf/performance.conf.erb.hidden > $HTTPD_CFG_DIR/performance.conf
-    enable_modules
-    ensure_valid_httpd_process "$HTTPD_PID_FILE" "$HTTPD_CFG_FILE"
+NGINX_EXEC=${OPENSHIFT_NGINX_VERSION_DIR}/sbin/nginx
+NGINX_CONFIG_FILE=${OPENSHIFT_NGINX_DIR}/conf/nginx.conf
+NGINX_HTTP_CONFIG_FILE=${OPENSHIFT_NGINX_DIR}/conf/nginx_http.conf
+
+PHP_FPM_EXEC=${OPENSHIFT_PHP_VERSION_DIR}/sbin/php-fpm
+PHP_FPM_PID=${OPENSHIFT_PHP_DIR}/pid/php-fpm-${OPENSHIFT_GEAR_UUID}.pid
+
+function isrunning() {
+    if [ -f "${OPENSHIFT_NGINX_PID}" ]; then
+        local pid=`cat ${OPENSHIFT_NGINX_PID} 2> /dev/null`
+        [ -z "${pid}" ]  &&  return 1
+
+        local current_user=`id -u`
+        if `ps --pid ${pid} > /dev/null 2>&1` || \
+           `pgrep -x nginx -u ${current_user} > /dev/null 2>&1`; then
+            return 0
+        fi
+    fi
+    return 1
 }
+
+function hasconfig() {
+    if [ ! -f "${NGINX_CONFIG_FILE}" ]; then
+        echo "Missing conf/nginx.conf in cartridge."
+        return 1
+    fi
+    if [ ! -f "${NGINX_HTTP_CONFIG_FILE}" ]; then
+        echo "Missing .openshift/nginx.conf.erb in repo."
+        return 1
+    fi
+
+    return 0
+}
+
+function _nginx_start() {
+    if hasconfig; then
+        ${NGINX_EXEC} -c ${NGINX_CONFIG_FILE} -p ${OPENSHIFT_NGINX_DIR} 2>&1
+
+        if [ $? -ne 0 ]; then
+            echo "Error starting nginx"
+        elif ! isrunning; then
+            local TIMEOUT="${STARTTIMEOUT}"
+            while [ ${TIMEOUT} -gt 0 ] && [ ! -f "${OPENSHIFT_NGINX_PID}" ]; do
+                sleep .5
+                let TIMEOUT=${TIMEOUT}-1
+            done
+        fi
+    fi
+}
+
+function _nginx_stop() {
+    [ -f "${OPENSHIFT_NGINX_PID}" ] && pid=$( /bin/cat "${OPENSHIFT_NGINX_PID}" )
+
+    # Check pid file
+    if `ps -p ${pid} > /dev/null 2>&1`; then
+        if hasconfig; then
+            ${NGINX_EXEC} -c ${NGINX_CONFIG_FILE} -p ${OPENSHIFT_NGINX_DIR} -s stop  2>&1
+        else
+            /bin/kill -9 ${pid}
+        fi
+
+        local ret=$?
+        if [ ${ret} -eq 0 ]; then
+            local TIMEOUT="${STOPTIMEOUT}"
+            while [ ${TIMEOUT} -gt 0 ] && [ -f "${OPENSHIFT_NGINX_PID}" ]; do
+                /bin/kill -0 "${pid}" >/dev/null 2>&1 || break
+                sleep .5
+                let TIMEOUT=${TIMEOUT}-1
+            done
+        fi
+    else
+        local current_user=`id -u`
+        if `pgrep -x nginx -u ${current_user} > /dev/null 2>&1`
+        then
+            echo "Warning: Nginx process exists without a pid file. Use force-stop to kill."
+        else
+            echo "Nginx already stopped"
+        fi
+    fi
+}
+
+function _nginx_update_conf() {
+    CONF_FILE=${OPENSHIFT_NGINX_DIR}/conf/nginx_http.conf.erb
+    if [ -f "${CONF_FILE}" ]; then
+        oo-erb ${CONF_FILE} > ${NGINX_HTTP_CONFIG_FILE}
+    else
+        echo "Failed updating .openshift/nginx.conf.erb, file not found"
+    fi
+}
+
+
+
 
 function start() {
-    echo "Starting DreamFactory ${OPENSHIFT_DREAMFACTORY_VERSION}"
-    pre_start_httpd_config
-    # Force httpd into its own pgroup, as httpd is hard-coded to TERM everything in
-    # its pgroup during shutdown (even while foregrounded)
-    set -m
-    php_context "nohup /usr/sbin/httpd $HTTPD_CMD_CONF -D FOREGROUND |& /usr/bin/logshifter -tag php &" \
-      && wait_for_pid_file $HTTPD_PID_FILE
-    set +m
-    return $?
-}
-
-function reload() {
-    echo "Reloading DreamFactory ${OPENSHIFT_DREAMFACTORY_VERSION}"
-    pre_start_httpd_config
-    httpd_pid=`cat "$HTTPD_PID_FILE" 2> /dev/null`
-    kill -USR1 $httpd_pid && wait_for_pid_file $HTTPD_PID_FILE
-    return $?
-}
-
-function restart() {
-    echo "Restarting DreamFactory ${OPENSHIFT_DREAMFACTORY_VERSION}"
-    ensure_httpd_restart_succeed "$HTTPD_PID_FILE" "$HTTPD_CFG_FILE"
-    if [ -f "$HTTPD_PID_FILE" ]; then
-        pre_start_httpd_config
-        httpd_pid=`cat "$HTTPD_PID_FILE" 2> /dev/null`
-        kill -HUP $httpd_pid
-    else
-        start
+    if isrunning; then
+        _nginx_stop
     fi
 
-    return $?
+    _nginx_update_conf
+    _nginx_start
+    isrunning && echo "Nginx instance is started"
+
+
+    config
+
+    if [ ${CONFIGURATION_DIRTY} -eq 1 ]; then
+        stop
+    fi
+
+    if ! _is_running; then
+
+        echo "Starting php fpm"
+        echo  ${PHP_FPM_EXEC}
+        echo "${OPENSHIFT_PHP_DIR}/conf/php-fpm.ini"
+        echo "${OPENSHIFT_PHP_DIR}/conf/php-fpm.conf"
+        echo "${OPENSHIFT_PHP_DIR}"
+
+        
+        # Start php fpm
+        ${PHP_FPM_EXEC} \
+            --php-ini "${OPENSHIFT_PHP_DIR}/conf/php-fpm.ini" \
+            --fpm-config "${OPENSHIFT_PHP_DIR}/conf/php-fpm.conf" \
+            --prefix "${OPENSHIFT_PHP_DIR}"
+
+        # _is_running && echo "PHP-FPM instance is started"
+    else
+        echo "PHP-FPM already running" 1>&2
+    fi
 }
+
 
 function stop() {
-    echo "Stopping DreamFactory ${OPENSHIFT_DREAMFACTORY_VERSION}"
-    ensure_valid_httpd_pid_file "$HTTPD_PID_FILE" "$HTTPD_CFG_FILE"
-    if [ -f "$HTTPD_PID_FILE" ]; then
-      # If we still have a PID file, then ensure_valid_httpd_process's call to
-      # killall_httpds didn't happen.
-      shutdown_httpd_graceful $HTTPD_PID_FILE
+    _nginx_stop
+    isrunning  ||  echo "Nginx instance is stopped"
+
+
+    [ -f "${PHP_FPM_PID}" ] && pid=$( /bin/cat "${PHP_FPM_PID}" )
+    if `ps -p ${pid} > /dev/null 2>&1`; then
+        /bin/kill ${pid}
+        ret=$?
+        if [ ${ret} -eq 0 ]; then
+            TIMEOUT="${STOPTIMEOUT}"
+            while [ ${TIMEOUT} -gt 0 ] && [ -f "${PHP_FPM_PID}" ]; do
+                /bin/kill -0 "${pid}" >/dev/null 2>&1 || break
+                sleep .5
+                let TIMEOUT=${TIMEOUT}-1
+            done
+        fi
+    else
+        if `pgrep -x php-fpm > /dev/null 2>&1`
+        then
+            echo "Warning: PHP-FPM process exists without a pid file.  Use force-stop to kill." 1>&2
+        else
+            echo "PHP-FPM already stopped" 1>&2
+        fi
     fi
+
+    ! _is_running && echo "PHP-FPM instance is stopped"
 }
 
-function configtest() {
-    echo "Testing Apache *.conf files"
-    php_context "/usr/sbin/httpd $HTTPD_CMD_CONF -t"
-    return $?
+
+function restart() {
+    _nginx_stop || pkill nginx || :
+    _nginx_start
+
+    isrunning  &&  echo "Restarted Nginx instance"
 }
+
 
 function status() {
-    if output=$(curl http://$OPENSHIFT_DREAMFACTORY_IP:$OPENSHIFT_DREAMFACTORY_PORT/server-status?auto 2>&1 ); then
-        client_result "Application is running"
-        client_result $output
+    if isrunning; then
+        client_result "Nginx is running"
     else
-        client_result "Application is either stopped or inaccessible"
+        client_result "Nginx is stopped"
     fi
+}
+
+
+function reload() {
+    if ! isrunning; then
+       _nginx_start
+    elif hasconfig; then
+       echo "`date`: Reloading Nginx " 1>&2
+        ${NGINX_EXEC} -c ${NGINX_CONFIG_FILE} -s reload 2>&1
+    fi
+
+    isrunning  &&  echo "Reloaded Nginx instance"
 }
 
 function tidy() {
-    echo "Emptying php logs in dir: $OPENSHIFT_LOG_DIR"
+    client_message "Emptying log dir: ${OPENSHIFT_NGINX_DIR}/logs"
     shopt -s dotglob
-    rm -rf $OPENSHIFT_LOG_DIR/php.log* || :
+    rm -rf logs/*
+}
+
+function update() {
+    _nginx_update_conf
 }
 
 function build() {
-    # Force clean build (.openshift/markers/force_clean_build)
-    if force_clean_build_enabled_for_latest_deployment; then
-        echo "Force clean build enabled - recreating PEARs"
-        mkdir -p ${OPENSHIFT_DREAMFACTORY_DIR}phplib/pear/{docs,ext,php,cache,cfg,data,download,temp,tests,www}
+    _nginx_update_conf
+
+    # Stop fpm if running
+    if _is_running; then
+        stop
     fi
 
-    # PEAR
-    local pear_file=.openshift/pear.txt
-    if [ -f ${OPENSHIFT_REPO_DIR}deplist.txt ]; then
-        if [ ! -f ${OPENSHIFT_REPO_DIR}${pear_file} ]; then
-            pear_file=deplist.txt
-            echo "The deplist.txt file was deprecated in favor of .openshift/pear.txt."
-            echo "Please consider running \`git mv deplist.txt .openshift/pear.txt' command."
-        else
-            echo "It appears you have a deplist.txt and .openshift/pear.txt file."
-            echo "Please consider running \`git rm deplist.txt'."
-        fi
-    fi
-    if [ -f ${OPENSHIFT_REPO_DIR}${pear_file} ]; then
-        echo "Checking ${pear_file} for PEAR dependency..."
-        local show_cleanbuild_msg=0
+    # Update configuration
+    config
 
-        for f in $(cat ${OPENSHIFT_REPO_DIR}${pear_file}); do
-            echo -e "Checking PEAR: $f\n"
-
-            if php_context "pear info '$f' &>/dev/null"; then # package is already installed
-
-                local current_version=$(pear info "$f" | awk '$0$1 ~/Release Version/ {print $3;}')
-                local desired_version=$(echo "$f" | sed -nre 's/^[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p')
-
-                if [ "$current_version" != "$desired_version" ]; then
-                    php_context "pear upgrade --alldeps '$f'" || show_cleanbuild_msg=1
-                fi
-            else
-                php_context "pear install --alldeps '$f'"
+    # Install pecl
+    PECL_FILE=${OPENSHIFT_REPO_DIR}/.openshift/php-pecl.txt
+    if [ -f ${PECL_FILE} ]; then
+        OLDIFS=$IFS
+        IFS=$'\n'
+        for pecl in $(cat ${PECL_FILE}); do
+            if [ ! -z ${pecl} ]; then
+                IFS=' ' read -a pecl_args <<< "${pecl}"
+                ${OPENSHIFT_PHP_DIR}/bin/install_pecl "${pecl_args[0]}" "${pecl_args[1]}" "${pecl_args[2]}"
             fi
-            echo
-            # Remove gear-specific absolute paths from the generated PEAR
-            # files except from the hidden dirs/files (cache, registry etc.)
-            find ${OPENSHIFT_DREAMFACTORY_DIR}phplib/pear/pear/ -type f \( ! -regex '.*/\..*' \) \
-              -exec sed -i "s|${OPENSHIFT_HOMEDIR}|~/|g" {} \;
         done
-
-        if [ $show_cleanbuild_msg -eq 1 ]; then
-            echo -e "Tip: Use the .openshift/markers/force_clean_build marker file to do a clean build.\n"
-            exit 1
-        fi
+        IFS=${OLDIFS}
     fi
 
-    # Composer
-    if [ -f ${OPENSHIFT_REPO_DIR}.openshift/markers/use_composer ]; then
-        local composer_lock_msg="\nPlease, consider committing the composer.lock file into your repository:\n"
-        composer_lock_msg+=" $ rhc scp ${OPENSHIFT_APP_NAME} download ./ app-root/repo/composer.lock\n"
-        composer_lock_msg+=" $ git add composer.lock && git commit -am'Lock specific set of Composer dependencies'\n"
-        if [ "${APPLICATION_ENV:-}" != "development" ]; then
-            # Production
-            echo -n "Checking composer.json for Composer dependency... "
-            if [ -f ${OPENSHIFT_REPO_DIR}composer.json ]; then
-                echo
-                composer install --no-interaction --no-ansi --no-scripts --optimize-autoloader --working-dir=${OPENSHIFT_REPO_DIR} || \
-                echo -e "\nSkipping Composer errors..\n\n  Please, fix the errors either locally or in development mode.\n"
-                if [ ! -f ${OPENSHIFT_REPO_DIR}composer.lock ]; then
-                    echo -e $composer_lock_msg
-                fi
-            else
-                echo "File not found."
-            fi
-        else
-            # Development
-            if [ -f ${OPENSHIFT_REPO_DIR}composer.lock ]; then
-                echo "Ignoring composer.lock file (development mode)"
-            fi
-            echo -n "Checking composer.json for Composer dependency... "
-            if [ -f ${OPENSHIFT_REPO_DIR}composer.json ]; then
-                echo
-                composer update --no-interaction --no-ansi --no-scripts --optimize-autoloader --working-dir=${OPENSHIFT_REPO_DIR}
-                echo -e $composer_lock_msg
-            else
-                echo "File not found."
-            fi
-        fi
+    # Composer self-update
+    COMPOSER_PATH=${PHP_VERSION_DIR}/bin/composer
+    if [ -f "${COMPOSER_PATH}" ]; then
+        ${COMPOSER_PATH} self-update
     fi
 }
 
+# function _forward_control_to_plugin() {
+#     # Because plugins don't receive some command we forward them
+#     if [ ! -z ${OPENSHIFT_PHP_DIR} ]; then
+#         ${OPENSHIFT_PHP_DIR}/bin/control "$1"
+#     fi
+# }
+
+function _is_running() {
+    if [ -f "${PHP_FPM_PID}" ]; then
+        local pid=`cat ${PHP_FPM_PID} 2> /dev/null`
+        [ -z "${pid}" ]  &&  return 1
+
+        local current_user=`id -u`
+        if `ps --pid ${pid} > /dev/null 2>&1` || \
+           `pgrep -x php-fpm -u ${current_user} > /dev/null 2>&1`; then
+            return 0
+        fi
+    fi
+    return 1
+}
+
 case "$1" in
-  start)           start ;;
-  stop)            stop ;;
-  restart)         restart ;;
-  reload|graceful) reload ;;
-  status)          status ;;
-  configtest)      configtest ;;
-  tidy)            tidy ;;
-  build)           build ;;
-  *)               exit 0
+  start)
+    start
+  ;;
+  stop)      stop ;;
+  restart)   restart ;;
+  status)    status ;;
+  reload)    reload ;;
+  tidy)      tidy ;;
+  update)
+    update
+  ;;
+  build)
+    build
+  ;;
+  *)         exit 0
 esac
 
-exit $?
+
